name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/docker-react -f Dockerfile.dev .
      - run: docker run aminetakha/docker-react yarn run test -- --watchAll=false
