name: Build and test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t aminetakha/docker-react -f Dockerfile.dev .
      - run: docker run aminetakha/docker-react yarn run test -- --watchAll=false
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENV_NAME }}
          existing_bucket_name: ${{ secrets.BUCKET_NAME }}
          region: ${{ secrets.REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
